import type { Exam } from '@/types';

export const mockExams: Exam[] = [
  {
    id: 'exam-1',
    title: 'Midterm: Data Structures & Algorithms',
    subject: 'Computer Science',
    duration: 120,
    totalMarks: 100,
    passingMarks: 60,
    status: 'live',
    startTime: '2024-06-21T09:00:00Z',
    endTime: '2024-06-21T11:00:00Z',
    institutionId: 'inst-1',
    teacherId: 'teacher-1',
    maxViolations: 3,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: true,
      shuffleOptions: true,
      showResultsAfter: true,
      allowedViolations: 3,
      proctoringLevel: 'strict',
    },
    createdAt: '2024-06-01T10:00:00Z',
    _count: { questions: 25, enrollments: 42 },
  },
  {
    id: 'exam-2',
    title: 'Final Exam: Calculus II',
    subject: 'Mathematics',
    duration: 180,
    totalMarks: 150,
    passingMarks: 90,
    status: 'scheduled',
    startTime: '2024-06-25T10:00:00Z',
    endTime: '2024-06-25T13:00:00Z',
    institutionId: 'inst-1',
    teacherId: 'teacher-1',
    maxViolations: 2,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: false,
      shuffleOptions: false,
      showResultsAfter: false,
      allowedViolations: 2,
      proctoringLevel: 'standard',
    },
    createdAt: '2024-06-05T14:00:00Z',
    _count: { questions: 30, enrollments: 38 },
  },
  {
    id: 'exam-3',
    title: 'Quiz 3: Introduction to Programming',
    subject: 'Computer Science',
    duration: 45,
    totalMarks: 50,
    passingMarks: 30,
    status: 'completed',
    startTime: '2024-06-10T14:00:00Z',
    endTime: '2024-06-10T14:45:00Z',
    institutionId: 'inst-1',
    teacherId: 'teacher-2',
    maxViolations: 5,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: true,
      shuffleOptions: true,
      showResultsAfter: true,
      allowedViolations: 5,
      proctoringLevel: 'basic',
    },
    createdAt: '2024-05-28T09:00:00Z',
    _count: { questions: 15, enrollments: 55 },
  },
  {
    id: 'exam-4',
    title: 'Organic Chemistry Midterm',
    subject: 'Chemistry',
    duration: 90,
    totalMarks: 80,
    passingMarks: 48,
    status: 'completed',
    startTime: '2024-06-08T09:00:00Z',
    endTime: '2024-06-08T10:30:00Z',
    institutionId: 'inst-1',
    teacherId: 'teacher-1',
    maxViolations: 3,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: true,
      shuffleOptions: false,
      showResultsAfter: true,
      allowedViolations: 3,
      proctoringLevel: 'standard',
    },
    createdAt: '2024-05-20T11:00:00Z',
    _count: { questions: 20, enrollments: 33 },
  },
  {
    id: 'exam-5',
    title: 'World History: Unit 4 Assessment',
    subject: 'History',
    duration: 60,
    totalMarks: 60,
    passingMarks: 36,
    status: 'draft',
    startTime: '2024-07-01T11:00:00Z',
    endTime: '2024-07-01T12:00:00Z',
    institutionId: 'inst-1',
    teacherId: 'teacher-2',
    maxViolations: 4,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: false,
      shuffleOptions: true,
      showResultsAfter: true,
      allowedViolations: 4,
      proctoringLevel: 'basic',
    },
    createdAt: '2024-06-18T08:00:00Z',
    _count: { questions: 10, enrollments: 0 },
  },
  {
    id: 'exam-6',
    title: 'Network Security Fundamentals',
    subject: 'Information Technology',
    duration: 120,
    totalMarks: 100,
    passingMarks: 70,
    status: 'scheduled',
    startTime: '2024-06-28T13:00:00Z',
    endTime: '2024-06-28T15:00:00Z',
    institutionId: 'inst-2',
    teacherId: 'teacher-3',
    maxViolations: 2,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: true,
      shuffleOptions: true,
      showResultsAfter: false,
      allowedViolations: 2,
      proctoringLevel: 'strict',
    },
    createdAt: '2024-06-10T10:00:00Z',
    _count: { questions: 40, enrollments: 28 },
  },
  {
    id: 'exam-7',
    title: 'Business Analytics Final',
    subject: 'Business Administration',
    duration: 150,
    totalMarks: 120,
    passingMarks: 72,
    status: 'live',
    startTime: '2024-06-21T08:00:00Z',
    endTime: '2024-06-21T10:30:00Z',
    institutionId: 'inst-2',
    teacherId: 'teacher-3',
    maxViolations: 3,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: false,
      shuffleOptions: false,
      showResultsAfter: true,
      allowedViolations: 3,
      proctoringLevel: 'standard',
    },
    createdAt: '2024-06-03T09:30:00Z',
    _count: { questions: 35, enrollments: 22 },
  },
  {
    id: 'exam-8',
    title: 'Python Programming Certification',
    subject: 'Computer Science',
    duration: 90,
    totalMarks: 100,
    passingMarks: 75,
    status: 'draft',
    startTime: '2024-07-05T10:00:00Z',
    endTime: '2024-07-05T11:30:00Z',
    institutionId: 'inst-3',
    teacherId: 'teacher-1',
    maxViolations: 2,
    isProctoringEnabled: true,
    settings: {
      shuffleQuestions: true,
      shuffleOptions: true,
      showResultsAfter: false,
      allowedViolations: 2,
      proctoringLevel: 'strict',
    },
    createdAt: '2024-06-19T14:00:00Z',
    _count: { questions: 0, enrollments: 0 },
  },
];
