import type { Item } from '@/types';

export const mockItems: Item[] = [
  {
    id: 'item-1',
    type: 'mcq',
    stem: 'What is the primary purpose of an operating system?',
    options: [
      { id: 'i1-a', text: 'Manage hardware resources', isCorrect: true },
      { id: 'i1-b', text: 'Run application software only', isCorrect: false },
      { id: 'i1-c', text: 'Store user files', isCorrect: false },
      { id: 'i1-d', text: 'Provide internet access', isCorrect: false },
    ],
    correctAnswer: 'i1-a',
    marks: 4,
    difficulty: 'easy',
    order: 1,
    status: 'approved',
    usageCount: 12,
    tags: ['OS', 'fundamentals', 'CS'],
    learningObjectiveId: 'clo-1',
    facilityIndex: 0.85,
    discriminationIndex: 0.42,
    version: 1,
    createdAt: '2024-05-01T10:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-2',
    type: 'mcq',
    stem: 'Which layer of the OSI model is responsible for routing packets between networks?',
    options: [
      { id: 'i2-a', text: 'Data Link Layer', isCorrect: false },
      { id: 'i2-b', text: 'Network Layer', isCorrect: true },
      { id: 'i2-c', text: 'Transport Layer', isCorrect: false },
      { id: 'i2-d', text: 'Physical Layer', isCorrect: false },
    ],
    correctAnswer: 'i2-b',
    marks: 4,
    difficulty: 'medium',
    order: 2,
    status: 'approved',
    usageCount: 8,
    tags: ['networking', 'OSI', 'protocols'],
    learningObjectiveId: 'clo-6',
    facilityIndex: 0.67,
    discriminationIndex: 0.58,
    version: 1,
    createdAt: '2024-05-03T11:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-3',
    type: 'essay',
    stem: 'Explain the concept of virtual memory and how it benefits modern operating systems. Discuss the role of page tables and TLB in virtual memory management.',
    marks: 20,
    difficulty: 'hard',
    order: 3,
    status: 'approved',
    usageCount: 3,
    tags: ['OS', 'memory management', 'advanced'],
    learningObjectiveId: 'clo-2',
    facilityIndex: 0.41,
    discriminationIndex: 0.71,
    version: 1,
    createdAt: '2024-05-05T09:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-4',
    type: 'true_false',
    stem: 'TCP is a connectionless protocol.',
    options: [
      { id: 'i4-t', text: 'True', isCorrect: false },
      { id: 'i4-f', text: 'False', isCorrect: true },
    ],
    correctAnswer: 'i4-f',
    marks: 2,
    difficulty: 'easy',
    order: 4,
    status: 'approved',
    usageCount: 15,
    tags: ['networking', 'protocols', 'TCP'],
    learningObjectiveId: 'clo-7',
    facilityIndex: 0.91,
    discriminationIndex: 0.18,
    version: 1,
    createdAt: '2024-05-07T14:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-5',
    type: 'mrq',
    stem: 'Which of the following are characteristics of a relational database? (Select all that apply)',
    options: [
      { id: 'i5-a', text: 'Data stored in tables', isCorrect: true },
      { id: 'i5-b', text: 'ACID transactions', isCorrect: true },
      { id: 'i5-c', text: 'Schemaless structure', isCorrect: false },
      { id: 'i5-d', text: 'SQL as query language', isCorrect: true },
    ],
    correctAnswer: ['i5-a', 'i5-b', 'i5-d'],
    marks: 6,
    difficulty: 'medium',
    order: 5,
    status: 'review',
    usageCount: 2,
    tags: ['databases', 'RDBMS', 'SQL'],
    facilityIndex: 0.55,
    discriminationIndex: 0.63,
    version: 1,
    createdAt: '2024-05-10T10:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-6',
    type: 'fill_blank',
    stem: 'The process of converting a high-level language into machine code is called ___.',
    correctAnswer: 'compilation',
    marks: 3,
    difficulty: 'easy',
    order: 6,
    status: 'approved',
    usageCount: 7,
    tags: ['programming', 'compilers', 'fundamentals'],
    learningObjectiveId: 'clo-4',
    facilityIndex: 0.78,
    discriminationIndex: 0.39,
    version: 1,
    createdAt: '2024-05-12T13:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-7',
    type: 'ordering',
    stem: 'Order the phases of the software development lifecycle from first to last:',
    options: [
      { id: 'i7-a', text: 'Requirements Analysis', isCorrect: true },
      { id: 'i7-b', text: 'System Design', isCorrect: true },
      { id: 'i7-c', text: 'Implementation', isCorrect: true },
      { id: 'i7-d', text: 'Testing and Maintenance', isCorrect: true },
    ],
    correctAnswer: ['i7-a', 'i7-b', 'i7-c', 'i7-d'],
    marks: 8,
    difficulty: 'medium',
    order: 7,
    status: 'review',
    usageCount: 1,
    tags: ['SDLC', 'software engineering', 'process'],
    learningObjectiveId: 'clo-10',
    facilityIndex: 0.48,
    discriminationIndex: 0.66,
    version: 1,
    createdAt: '2024-05-15T09:00:00Z',
    authorId: 'teacher-3',
  },
  {
    id: 'item-8',
    type: 'mcq',
    stem: 'In object-oriented programming, what is encapsulation?',
    options: [
      { id: 'i8-a', text: 'Creating multiple objects from one class', isCorrect: false },
      { id: 'i8-b', text: 'Inheriting properties from a parent class', isCorrect: false },
      { id: 'i8-c', text: 'Bundling data and methods that operate on the data within one unit', isCorrect: true },
      { id: 'i8-d', text: 'Overriding parent class methods', isCorrect: false },
    ],
    correctAnswer: 'i8-c',
    marks: 4,
    difficulty: 'medium',
    order: 8,
    status: 'approved',
    usageCount: 10,
    tags: ['OOP', 'programming', 'design'],
    learningObjectiveId: 'clo-5',
    facilityIndex: 0.72,
    discriminationIndex: 0.51,
    version: 1,
    createdAt: '2024-05-17T11:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-9',
    type: 'short_answer',
    stem: 'What does REST stand for in web development?',
    correctAnswer: 'Representational State Transfer',
    marks: 3,
    difficulty: 'easy',
    order: 9,
    status: 'approved',
    usageCount: 6,
    tags: ['web', 'API', 'REST'],
    facilityIndex: 0.82,
    discriminationIndex: 0.29,
    version: 1,
    createdAt: '2024-05-19T10:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-10',
    type: 'essay',
    stem: 'Compare and contrast microservices architecture with monolithic architecture. Discuss the trade-offs and provide examples of when each approach is most suitable.',
    marks: 25,
    difficulty: 'hard',
    order: 10,
    status: 'review',
    usageCount: 0,
    tags: ['architecture', 'microservices', 'design patterns'],
    facilityIndex: 0.33,
    discriminationIndex: 0.74,
    version: 1,
    createdAt: '2024-05-21T14:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-11',
    type: 'mcq',
    stem: 'Which sorting algorithm has the best worst-case time complexity?',
    options: [
      { id: 'i11-a', text: 'Quick Sort', isCorrect: false },
      { id: 'i11-b', text: 'Bubble Sort', isCorrect: false },
      { id: 'i11-c', text: 'Merge Sort', isCorrect: true },
      { id: 'i11-d', text: 'Selection Sort', isCorrect: false },
    ],
    correctAnswer: 'i11-c',
    marks: 4,
    difficulty: 'medium',
    order: 11,
    status: 'approved',
    usageCount: 9,
    tags: ['algorithms', 'sorting', 'complexity'],
    learningObjectiveId: 'clo-3',
    facilityIndex: 0.61,
    discriminationIndex: 0.67,
    version: 1,
    createdAt: '2024-05-22T09:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-12',
    type: 'true_false',
    stem: 'IPv6 addresses are 32 bits long.',
    options: [
      { id: 'i12-t', text: 'True', isCorrect: false },
      { id: 'i12-f', text: 'False', isCorrect: true },
    ],
    correctAnswer: 'i12-f',
    marks: 2,
    difficulty: 'easy',
    order: 12,
    status: 'approved',
    usageCount: 11,
    tags: ['networking', 'IPv6', 'protocols'],
    learningObjectiveId: 'clo-6',
    facilityIndex: 0.88,
    discriminationIndex: 0.21,
    version: 1,
    createdAt: '2024-05-23T10:00:00Z',
    authorId: 'teacher-3',
  },
  {
    id: 'item-13',
    type: 'mcq',
    stem: 'What is the primary advantage of using a NoSQL database over a relational database?',
    options: [
      { id: 'i13-a', text: 'Stronger ACID compliance', isCorrect: false },
      { id: 'i13-b', text: 'Better for highly structured data', isCorrect: false },
      { id: 'i13-c', text: 'Horizontal scalability and flexible schema', isCorrect: true },
      { id: 'i13-d', text: 'Simpler query language', isCorrect: false },
    ],
    correctAnswer: 'i13-c',
    marks: 4,
    difficulty: 'medium',
    order: 13,
    status: 'review',
    usageCount: 4,
    tags: ['databases', 'NoSQL', 'scalability'],
    facilityIndex: 0.59,
    discriminationIndex: 0.55,
    version: 1,
    createdAt: '2024-05-24T11:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-14',
    type: 'short_answer',
    stem: 'In Big O notation, what is the time complexity of accessing an element by index in an array?',
    correctAnswer: 'O(1)',
    marks: 3,
    difficulty: 'easy',
    order: 14,
    status: 'approved',
    usageCount: 13,
    tags: ['algorithms', 'arrays', 'complexity'],
    learningObjectiveId: 'clo-3',
    facilityIndex: 0.94,
    discriminationIndex: 0.12,
    version: 1,
    createdAt: '2024-05-25T09:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-15',
    type: 'mcq',
    stem: 'Which design pattern provides a single point of access to a class with only one instance?',
    options: [
      { id: 'i15-a', text: 'Factory Pattern', isCorrect: false },
      { id: 'i15-b', text: 'Observer Pattern', isCorrect: false },
      { id: 'i15-c', text: 'Singleton Pattern', isCorrect: true },
      { id: 'i15-d', text: 'Strategy Pattern', isCorrect: false },
    ],
    correctAnswer: 'i15-c',
    marks: 4,
    difficulty: 'medium',
    order: 15,
    status: 'draft',
    usageCount: 0,
    tags: ['design patterns', 'OOP', 'architecture'],
    learningObjectiveId: 'clo-11',
    facilityIndex: 0.69,
    discriminationIndex: 0.48,
    version: 1,
    createdAt: '2024-06-01T10:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-16',
    type: 'fill_blank',
    stem: 'In Python, a dictionary uses ___ to store key-value pairs.',
    correctAnswer: 'hashing',
    marks: 3,
    difficulty: 'medium',
    order: 16,
    status: 'draft',
    usageCount: 0,
    tags: ['Python', 'data structures', 'hashing'],
    learningObjectiveId: 'clo-4',
    version: 1,
    createdAt: '2024-06-05T14:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-17',
    type: 'mrq',
    stem: 'Which HTTP methods are considered "safe" (do not modify server state)? (Select all that apply)',
    options: [
      { id: 'i17-a', text: 'GET', isCorrect: true },
      { id: 'i17-b', text: 'POST', isCorrect: false },
      { id: 'i17-c', text: 'HEAD', isCorrect: true },
      { id: 'i17-d', text: 'OPTIONS', isCorrect: true },
    ],
    correctAnswer: ['i17-a', 'i17-c', 'i17-d'],
    marks: 6,
    difficulty: 'medium',
    order: 17,
    status: 'review',
    usageCount: 3,
    tags: ['web', 'HTTP', 'API'],
    learningObjectiveId: 'clo-9',
    facilityIndex: 0.44,
    discriminationIndex: 0.62,
    version: 1,
    createdAt: '2024-06-08T09:00:00Z',
    authorId: 'teacher-3',
  },
  {
    id: 'item-18',
    type: 'essay',
    stem: 'Describe three common web security vulnerabilities (from the OWASP Top 10), explaining how each can be exploited and what measures can be taken to prevent them.',
    marks: 30,
    difficulty: 'hard',
    order: 18,
    status: 'approved',
    usageCount: 2,
    tags: ['security', 'OWASP', 'web development'],
    learningObjectiveId: 'clo-8',
    facilityIndex: 0.29,
    discriminationIndex: 0.78,
    version: 1,
    createdAt: '2024-06-10T10:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-19',
    type: 'mcq',
    stem: 'What is the purpose of database indexing?',
    options: [
      { id: 'i19-a', text: 'To reduce storage space', isCorrect: false },
      { id: 'i19-b', text: 'To speed up data retrieval operations', isCorrect: true },
      { id: 'i19-c', text: 'To enforce data integrity', isCorrect: false },
      { id: 'i19-d', text: 'To encrypt sensitive data', isCorrect: false },
    ],
    correctAnswer: 'i19-b',
    marks: 4,
    difficulty: 'easy',
    order: 19,
    status: 'approved',
    usageCount: 7,
    tags: ['databases', 'indexing', 'performance'],
    facilityIndex: 0.76,
    discriminationIndex: 0.44,
    version: 1,
    createdAt: '2024-06-12T11:00:00Z',
    authorId: 'teacher-2',
  },
  {
    id: 'item-20',
    type: 'ordering',
    stem: 'Order the OSI model layers from bottom (Layer 1) to top (Layer 7):',
    options: [
      { id: 'i20-a', text: 'Physical', isCorrect: true },
      { id: 'i20-b', text: 'Data Link', isCorrect: true },
      { id: 'i20-c', text: 'Network', isCorrect: true },
      { id: 'i20-d', text: 'Application', isCorrect: true },
    ],
    correctAnswer: ['i20-a', 'i20-b', 'i20-c', 'i20-d'],
    marks: 8,
    difficulty: 'medium',
    order: 20,
    status: 'draft',
    usageCount: 0,
    tags: ['networking', 'OSI', 'fundamentals'],
    learningObjectiveId: 'clo-6',
    version: 1,
    createdAt: '2024-06-15T09:00:00Z',
    authorId: 'teacher-3',
  },
  {
    id: 'item-21',
    type: 'short_answer',
    stem: 'What does SOLID stand for in software engineering principles?',
    correctAnswer: 'Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion',
    marks: 5,
    difficulty: 'hard',
    order: 21,
    status: 'review',
    usageCount: 1,
    tags: ['software engineering', 'SOLID', 'principles'],
    learningObjectiveId: 'clo-10',
    facilityIndex: 0.22,
    discriminationIndex: 0.69,
    version: 1,
    createdAt: '2024-06-17T10:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-22',
    type: 'matching',
    stem: 'Match each concept with its correct definition:',
    options: [
      { id: 'i22-a', text: 'Polymorphism — Same interface, different implementations', isCorrect: true },
      { id: 'i22-b', text: 'Abstraction — Hiding implementation details', isCorrect: true },
      { id: 'i22-c', text: 'Inheritance — Deriving new class from existing class', isCorrect: true },
      { id: 'i22-d', text: 'Encapsulation — Bundling data with methods', isCorrect: true },
    ],
    correctAnswer: ['i22-a', 'i22-b', 'i22-c', 'i22-d'],
    marks: 8,
    difficulty: 'medium',
    order: 22,
    status: 'approved',
    usageCount: 5,
    tags: ['OOP', 'concepts', 'programming'],
    learningObjectiveId: 'clo-5',
    facilityIndex: 0.57,
    discriminationIndex: 0.59,
    version: 1,
    createdAt: '2024-06-18T09:00:00Z',
    authorId: 'teacher-2',
  },
  // ── New question types (Phase 1 additions per EvaliX spec) ──────────────────
  {
    id: 'item-23',
    type: 'coding',
    stem: 'Write a Python function `fibonacci(n)` that returns the nth Fibonacci number using recursion. The function should handle edge cases where n=0 returns 0 and n=1 returns 1.',
    codeLanguage: 'python',
    starterCode: 'def fibonacci(n):\n    # Your code here\n    pass\n',
    testCases: [
      { input: '0', expectedOutput: '0', isHidden: false },
      { input: '1', expectedOutput: '1', isHidden: false },
      { input: '10', expectedOutput: '55', isHidden: true },
      { input: '15', expectedOutput: '610', isHidden: true },
    ],
    marks: 15,
    difficulty: 'medium',
    order: 23,
    status: 'approved',
    usageCount: 0,
    tags: ['python', 'recursion', 'fibonacci', 'algorithms'],
    learningObjectiveId: 'clo-4',
    facilityIndex: 0.52,
    discriminationIndex: 0.64,
    version: 1,
    createdAt: '2024-06-20T10:00:00Z',
    authorId: 'teacher-1',
  },
  {
    id: 'item-24',
    type: 'file_upload',
    stem: 'Design a complete Entity-Relationship (ER) diagram for a university database system that includes Students, Courses, Instructors, Enrollments, and Grades. Upload your diagram as a PDF or image file.',
    allowedFileTypes: ['.pdf', '.png', '.jpg', '.jpeg'],
    maxFileSizeMB: 10,
    marks: 20,
    difficulty: 'hard',
    order: 24,
    status: 'approved',
    usageCount: 0,
    tags: ['databases', 'ER diagram', 'design', 'applied'],
    learningObjectiveId: 'clo-4',
    facilityIndex: 0.38,
    discriminationIndex: 0.73,
    version: 1,
    createdAt: '2024-06-21T10:00:00Z',
    authorId: 'teacher-1',
  },
];
