import type { Question } from '@/types';

export const mockQuestions: Question[] = [
  // exam-1: Data Structures & Algorithms
  {
    id: 'q-1',
    examId: 'exam-1',
    type: 'mcq',
    stem: 'What is the time complexity of binary search on a sorted array of n elements?',
    options: [
      { id: 'q1-a', text: 'O(n)', isCorrect: false },
      { id: 'q1-b', text: 'O(log n)', isCorrect: true },
      { id: 'q1-c', text: 'O(n log n)', isCorrect: false },
      { id: 'q1-d', text: 'O(1)', isCorrect: false },
    ],
    correctAnswer: 'q1-b',
    marks: 4,
    difficulty: 'easy',
    order: 1,
    explanation: 'Binary search divides the search space in half each iteration, resulting in O(log n) complexity.',
  },
  {
    id: 'q-2',
    examId: 'exam-1',
    type: 'mcq',
    stem: 'Which data structure operates on the principle of LIFO (Last In, First Out)?',
    options: [
      { id: 'q2-a', text: 'Queue', isCorrect: false },
      { id: 'q2-b', text: 'Stack', isCorrect: true },
      { id: 'q2-c', text: 'Linked List', isCorrect: false },
      { id: 'q2-d', text: 'Deque', isCorrect: false },
    ],
    correctAnswer: 'q2-b',
    marks: 4,
    difficulty: 'easy',
    order: 2,
  },
  {
    id: 'q-3',
    examId: 'exam-1',
    type: 'mrq',
    stem: 'Which of the following are valid graph traversal algorithms? (Select all that apply)',
    options: [
      { id: 'q3-a', text: 'Depth-First Search (DFS)', isCorrect: true },
      { id: 'q3-b', text: 'Breadth-First Search (BFS)', isCorrect: true },
      { id: 'q3-c', text: 'Binary Search', isCorrect: false },
      { id: 'q3-d', text: "Dijkstra's Algorithm", isCorrect: true },
    ],
    correctAnswer: ['q3-a', 'q3-b', 'q3-d'],
    marks: 6,
    difficulty: 'medium',
    order: 3,
  },
  {
    id: 'q-4',
    examId: 'exam-1',
    type: 'true_false',
    stem: 'A Hash Table provides O(1) average time complexity for both insert and lookup operations.',
    options: [
      { id: 'q4-t', text: 'True', isCorrect: true },
      { id: 'q4-f', text: 'False', isCorrect: false },
    ],
    correctAnswer: 'q4-t',
    marks: 3,
    difficulty: 'easy',
    order: 4,
  },
  {
    id: 'q-5',
    examId: 'exam-1',
    type: 'short_answer',
    stem: 'What is the worst-case space complexity of Merge Sort?',
    correctAnswer: 'O(n)',
    marks: 5,
    difficulty: 'medium',
    order: 5,
  },
  {
    id: 'q-6',
    examId: 'exam-1',
    type: 'essay',
    stem: 'Explain the difference between a min-heap and a max-heap. Describe an algorithm for converting a max-heap to a min-heap and analyze its time complexity.',
    marks: 15,
    difficulty: 'hard',
    order: 6,
  },
  {
    id: 'q-7',
    examId: 'exam-1',
    type: 'fill_blank',
    stem: 'In a balanced binary search tree with n nodes, the height is approximately ___.',
    correctAnswer: 'log n',
    marks: 4,
    difficulty: 'medium',
    order: 7,
  },
  {
    id: 'q-8',
    examId: 'exam-1',
    type: 'ordering',
    stem: 'Order the following sorting algorithms from best to worst average-case time complexity:',
    options: [
      { id: 'q8-a', text: 'Bubble Sort O(n²)', isCorrect: false },
      { id: 'q8-b', text: 'Quick Sort O(n log n)', isCorrect: true },
      { id: 'q8-c', text: 'Merge Sort O(n log n)', isCorrect: true },
      { id: 'q8-d', text: 'Counting Sort O(n+k)', isCorrect: false },
    ],
    correctAnswer: ['q8-d', 'q8-b', 'q8-c', 'q8-a'],
    marks: 8,
    difficulty: 'hard',
    order: 8,
  },
  // exam-2: Calculus II
  {
    id: 'q-9',
    examId: 'exam-2',
    type: 'mcq',
    stem: 'What is the integral of sin(x) with respect to x?',
    options: [
      { id: 'q9-a', text: 'cos(x) + C', isCorrect: false },
      { id: 'q9-b', text: '-cos(x) + C', isCorrect: true },
      { id: 'q9-c', text: 'sin(x) + C', isCorrect: false },
      { id: 'q9-d', text: '-sin(x) + C', isCorrect: false },
    ],
    correctAnswer: 'q9-b',
    marks: 5,
    difficulty: 'easy',
    order: 1,
  },
  {
    id: 'q-10',
    examId: 'exam-2',
    type: 'mcq',
    stem: 'Which test is used to determine if a series converges by comparing it to a known convergent series?',
    options: [
      { id: 'q10-a', text: 'Ratio Test', isCorrect: false },
      { id: 'q10-b', text: 'Comparison Test', isCorrect: true },
      { id: 'q10-c', text: 'Integral Test', isCorrect: false },
      { id: 'q10-d', text: 'Root Test', isCorrect: false },
    ],
    correctAnswer: 'q10-b',
    marks: 5,
    difficulty: 'medium',
    order: 2,
  },
  {
    id: 'q-11',
    examId: 'exam-2',
    type: 'essay',
    stem: 'Evaluate the improper integral ∫(1 to ∞) 1/x² dx. Show all work and state whether the integral converges or diverges.',
    marks: 20,
    difficulty: 'hard',
    order: 3,
  },
  // exam-3: Intro to Programming
  {
    id: 'q-12',
    examId: 'exam-3',
    type: 'mcq',
    stem: 'What keyword is used to define a function in Python?',
    options: [
      { id: 'q12-a', text: 'function', isCorrect: false },
      { id: 'q12-b', text: 'define', isCorrect: false },
      { id: 'q12-c', text: 'def', isCorrect: true },
      { id: 'q12-d', text: 'func', isCorrect: false },
    ],
    correctAnswer: 'q12-c',
    marks: 3,
    difficulty: 'easy',
    order: 1,
  },
  {
    id: 'q-13',
    examId: 'exam-3',
    type: 'true_false',
    stem: 'In Python, variables must be declared with a specific type before use.',
    options: [
      { id: 'q13-t', text: 'True', isCorrect: false },
      { id: 'q13-f', text: 'False', isCorrect: true },
    ],
    correctAnswer: 'q13-f',
    marks: 2,
    difficulty: 'easy',
    order: 2,
  },
  {
    id: 'q-14',
    examId: 'exam-3',
    type: 'short_answer',
    stem: 'What is the output of print(len("Hello World"))?',
    correctAnswer: '11',
    marks: 3,
    difficulty: 'easy',
    order: 3,
  },
  {
    id: 'q-15',
    examId: 'exam-3',
    type: 'mcq',
    stem: 'Which of the following is NOT a valid Python data type?',
    options: [
      { id: 'q15-a', text: 'list', isCorrect: false },
      { id: 'q15-b', text: 'dict', isCorrect: false },
      { id: 'q15-c', text: 'array', isCorrect: true },
      { id: 'q15-d', text: 'tuple', isCorrect: false },
    ],
    correctAnswer: 'q15-c',
    marks: 3,
    difficulty: 'medium',
    order: 4,
  },
  {
    id: 'q-16',
    examId: 'exam-3',
    type: 'mrq',
    stem: 'Which of the following are Python loop types? (Select all that apply)',
    options: [
      { id: 'q16-a', text: 'for', isCorrect: true },
      { id: 'q16-b', text: 'while', isCorrect: true },
      { id: 'q16-c', text: 'do-while', isCorrect: false },
      { id: 'q16-d', text: 'foreach', isCorrect: false },
    ],
    correctAnswer: ['q16-a', 'q16-b'],
    marks: 4,
    difficulty: 'easy',
    order: 5,
  },
  // exam-4: Organic Chemistry
  {
    id: 'q-17',
    examId: 'exam-4',
    type: 'mcq',
    stem: 'Which functional group is characteristic of carboxylic acids?',
    options: [
      { id: 'q17-a', text: '-OH', isCorrect: false },
      { id: 'q17-b', text: '-COOH', isCorrect: true },
      { id: 'q17-c', text: '-CHO', isCorrect: false },
      { id: 'q17-d', text: '-CO-', isCorrect: false },
    ],
    correctAnswer: 'q17-b',
    marks: 4,
    difficulty: 'easy',
    order: 1,
  },
  {
    id: 'q-18',
    examId: 'exam-4',
    type: 'mcq',
    stem: 'What type of reaction converts an alkene to a haloalkane?',
    options: [
      { id: 'q18-a', text: 'Substitution', isCorrect: false },
      { id: 'q18-b', text: 'Elimination', isCorrect: false },
      { id: 'q18-c', text: 'Addition', isCorrect: true },
      { id: 'q18-d', text: 'Rearrangement', isCorrect: false },
    ],
    correctAnswer: 'q18-c',
    marks: 4,
    difficulty: 'medium',
    order: 2,
  },
  {
    id: 'q-19',
    examId: 'exam-4',
    type: 'essay',
    stem: 'Draw and explain the mechanism of the SN2 reaction of 1-bromobutane with sodium hydroxide. Include all relevant curved arrows and intermediates.',
    marks: 20,
    difficulty: 'hard',
    order: 3,
  },
  // exam-6: Network Security
  {
    id: 'q-20',
    examId: 'exam-6',
    type: 'mcq',
    stem: 'Which protocol provides encryption for data in transit over a network?',
    options: [
      { id: 'q20-a', text: 'HTTP', isCorrect: false },
      { id: 'q20-b', text: 'FTP', isCorrect: false },
      { id: 'q20-c', text: 'TLS', isCorrect: true },
      { id: 'q20-d', text: 'SMTP', isCorrect: false },
    ],
    correctAnswer: 'q20-c',
    marks: 4,
    difficulty: 'easy',
    order: 1,
  },
  {
    id: 'q-21',
    examId: 'exam-6',
    type: 'mrq',
    stem: 'Which of the following are types of network attacks? (Select all that apply)',
    options: [
      { id: 'q21-a', text: 'DDoS', isCorrect: true },
      { id: 'q21-b', text: 'Man-in-the-Middle', isCorrect: true },
      { id: 'q21-c', text: 'DNS Caching', isCorrect: false },
      { id: 'q21-d', text: 'SQL Injection', isCorrect: true },
    ],
    correctAnswer: ['q21-a', 'q21-b', 'q21-d'],
    marks: 6,
    difficulty: 'medium',
    order: 2,
  },
  {
    id: 'q-22',
    examId: 'exam-6',
    type: 'true_false',
    stem: 'A firewall can protect a network from all types of cyberattacks.',
    options: [
      { id: 'q22-t', text: 'True', isCorrect: false },
      { id: 'q22-f', text: 'False', isCorrect: true },
    ],
    correctAnswer: 'q22-f',
    marks: 3,
    difficulty: 'easy',
    order: 3,
  },
  {
    id: 'q-23',
    examId: 'exam-6',
    type: 'essay',
    stem: 'Describe the concept of Defense in Depth in cybersecurity. Give three concrete examples of how it applies to protecting a corporate network.',
    marks: 20,
    difficulty: 'hard',
    order: 4,
  },
  // exam-7: Business Analytics
  {
    id: 'q-24',
    examId: 'exam-7',
    type: 'mcq',
    stem: 'Which statistical measure represents the middle value in a sorted dataset?',
    options: [
      { id: 'q24-a', text: 'Mean', isCorrect: false },
      { id: 'q24-b', text: 'Median', isCorrect: true },
      { id: 'q24-c', text: 'Mode', isCorrect: false },
      { id: 'q24-d', text: 'Variance', isCorrect: false },
    ],
    correctAnswer: 'q24-b',
    marks: 4,
    difficulty: 'easy',
    order: 1,
  },
  {
    id: 'q-25',
    examId: 'exam-7',
    type: 'mcq',
    stem: 'In regression analysis, what does an R² value of 0.85 indicate?',
    options: [
      { id: 'q25-a', text: '85% of data is accurate', isCorrect: false },
      { id: 'q25-b', text: '85% of variance in the dependent variable is explained', isCorrect: true },
      { id: 'q25-c', text: 'The model has 85% precision', isCorrect: false },
      { id: 'q25-d', text: '15% of predictions are wrong', isCorrect: false },
    ],
    correctAnswer: 'q25-b',
    marks: 5,
    difficulty: 'medium',
    order: 2,
  },
  {
    id: 'q-26',
    examId: 'exam-7',
    type: 'essay',
    stem: 'A retail company wants to predict next quarter sales. Describe a data analytics approach, including what data to collect, which model to use, and how to evaluate its performance.',
    marks: 25,
    difficulty: 'hard',
    order: 3,
  },
  // Additional questions for variety
  {
    id: 'q-27',
    examId: 'exam-1',
    type: 'matching',
    stem: 'Match each data structure with its primary use case:',
    options: [
      { id: 'q27-a', text: 'Stack — Function call management', isCorrect: true },
      { id: 'q27-b', text: 'Queue — BFS traversal', isCorrect: true },
      { id: 'q27-c', text: 'Heap — Priority scheduling', isCorrect: true },
      { id: 'q27-d', text: 'Graph — Network routing', isCorrect: true },
    ],
    correctAnswer: ['q27-a', 'q27-b', 'q27-c', 'q27-d'],
    marks: 8,
    difficulty: 'medium',
    order: 9,
  },
  {
    id: 'q-28',
    examId: 'exam-2',
    type: 'fill_blank',
    stem: 'The derivative of e^x is ___.',
    correctAnswer: 'e^x',
    marks: 5,
    difficulty: 'easy',
    order: 4,
  },
  {
    id: 'q-29',
    examId: 'exam-3',
    type: 'short_answer',
    stem: 'Write a one-line Python list comprehension that generates squares of numbers 1 through 10.',
    correctAnswer: '[x**2 for x in range(1, 11)]',
    marks: 5,
    difficulty: 'medium',
    order: 6,
  },
  {
    id: 'q-30',
    examId: 'exam-1',
    type: 'mcq',
    stem: 'What is the average case time complexity of QuickSort?',
    options: [
      { id: 'q30-a', text: 'O(n)', isCorrect: false },
      { id: 'q30-b', text: 'O(n log n)', isCorrect: true },
      { id: 'q30-c', text: 'O(n²)', isCorrect: false },
      { id: 'q30-d', text: 'O(log n)', isCorrect: false },
    ],
    correctAnswer: 'q30-b',
    marks: 4,
    difficulty: 'medium',
    order: 10,
  },
];
