import type { CurrentUser } from '@/types';

export const mockUsers: CurrentUser[] = [
  {
    id: 'admin-1',
    name: 'Dr. Ahmad Hassan',
    email: 'ahmad.hassan@university.edu',
    role: 'admin',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'teacher-1',
    name: 'Dr. Sarah Mitchell',
    email: 'sarah.mitchell@university.edu',
    role: 'teacher',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'teacher-2',
    name: 'Prof. James Chen',
    email: 'james.chen@university.edu',
    role: 'teacher',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'teacher-3',
    name: 'Dr. Amina Hassan',
    email: 'amina.hassan@techcollege.edu',
    role: 'teacher',
    institutionId: 'inst-2',
    avatarUrl: undefined,
  },
  {
    id: 'student-1',
    name: 'Alex Thompson',
    email: 'alex.thompson@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-2',
    name: 'Maria Garcia',
    email: 'maria.garcia@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-3',
    name: 'Liam Johnson',
    email: 'liam.johnson@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-4',
    name: 'Fatima Al-Rashid',
    email: 'fatima.rashid@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-5',
    name: 'Noah Williams',
    email: 'noah.williams@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-6',
    name: 'Emma Davis',
    email: 'emma.davis@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-7',
    name: 'Oliver Brown',
    email: 'oliver.brown@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-8',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@student.edu',
    role: 'student',
    institutionId: 'inst-1',
    avatarUrl: undefined,
  },
  {
    id: 'student-9',
    name: 'Aiden Wilson',
    email: 'aiden.wilson@student.edu',
    role: 'student',
    institutionId: 'inst-2',
    avatarUrl: undefined,
  },
  {
    id: 'student-10',
    name: 'Isabella Lee',
    email: 'isabella.lee@student.edu',
    role: 'student',
    institutionId: 'inst-2',
    avatarUrl: undefined,
  },
  {
    id: 'student-11',
    name: 'Lucas Taylor',
    email: 'lucas.taylor@student.edu',
    role: 'student',
    institutionId: 'inst-2',
    avatarUrl: undefined,
  },
  {
    id: 'student-12',
    name: 'Mia Anderson',
    email: 'mia.anderson@student.edu',
    role: 'student',
    institutionId: 'inst-2',
    avatarUrl: undefined,
  },
  {
    id: 'student-13',
    name: 'Ethan Thomas',
    email: 'ethan.thomas@student.edu',
    role: 'student',
    institutionId: 'inst-2',
    avatarUrl: undefined,
  },
  {
    id: 'student-14',
    name: 'Charlotte White',
    email: 'charlotte.white@student.edu',
    role: 'student',
    institutionId: 'inst-3',
    avatarUrl: undefined,
  },
  {
    id: 'student-15',
    name: 'James Harris',
    email: 'james.harris@student.edu',
    role: 'student',
    institutionId: 'inst-3',
    avatarUrl: undefined,
  },
];
