import type { Violation } from '@/types';

export const mockViolations: Violation[] = [
  {
    id: 'v-1',
    attemptId: 'attempt-1',
    studentId: 'student-1',
    examId: 'exam-1',
    type: 'tab_switch',
    severity: 'medium',
    timestamp: '2024-06-21T09:15:23Z',
    description: 'Student switched to another browser tab',
  },
  {
    id: 'v-2',
    attemptId: 'attempt-1',
    studentId: 'student-1',
    examId: 'exam-1',
    type: 'fullscreen_exit',
    severity: 'high',
    timestamp: '2024-06-21T09:22:45Z',
    description: 'Student exited fullscreen mode',
  },
  {
    id: 'v-3',
    attemptId: 'attempt-2',
    studentId: 'student-2',
    examId: 'exam-1',
    type: 'no_face',
    severity: 'high',
    timestamp: '2024-06-21T09:30:12Z',
    description: 'No face detected in camera feed for 30 seconds',
  },
  {
    id: 'v-4',
    attemptId: 'attempt-3',
    studentId: 'student-3',
    examId: 'exam-1',
    type: 'audio_detected',
    severity: 'medium',
    timestamp: '2024-06-21T09:35:07Z',
    description: 'Sustained audio above threshold detected',
  },
  {
    id: 'v-5',
    attemptId: 'attempt-4',
    studentId: 'student-4',
    examId: 'exam-1',
    type: 'multiple_faces',
    severity: 'high',
    timestamp: '2024-06-21T09:42:33Z',
    description: 'Multiple faces detected in camera frame',
  },
  {
    id: 'v-6',
    attemptId: 'attempt-5',
    studentId: 'student-5',
    examId: 'exam-1',
    type: 'window_blur',
    severity: 'low',
    timestamp: '2024-06-21T09:48:19Z',
    description: 'Browser window lost focus',
  },
  {
    id: 'v-7',
    attemptId: 'attempt-6',
    studentId: 'student-6',
    examId: 'exam-1',
    type: 'tab_switch',
    severity: 'medium',
    timestamp: '2024-06-21T09:52:44Z',
    description: 'Student switched to another browser tab',
  },
  {
    id: 'v-8',
    attemptId: 'attempt-7',
    studentId: 'student-7',
    examId: 'exam-1',
    type: 'phone_detected',
    severity: 'high',
    timestamp: '2024-06-21T10:01:15Z',
    description: 'Mobile phone detected in camera view',
  },
  {
    id: 'v-9',
    attemptId: 'attempt-2',
    studentId: 'student-2',
    examId: 'exam-1',
    type: 'tab_switch',
    severity: 'medium',
    timestamp: '2024-06-21T10:05:30Z',
    description: 'Student switched to another browser tab (second occurrence)',
  },
  {
    id: 'v-10',
    attemptId: 'attempt-8',
    studentId: 'student-8',
    examId: 'exam-1',
    type: 'fullscreen_exit',
    severity: 'high',
    timestamp: '2024-06-21T10:12:22Z',
    description: 'Student exited fullscreen mode',
  },
  {
    id: 'v-11',
    attemptId: 'attempt-9',
    studentId: 'student-9',
    examId: 'exam-7',
    type: 'audio_detected',
    severity: 'low',
    timestamp: '2024-06-21T08:20:55Z',
    description: 'Low-level audio detected briefly',
  },
  {
    id: 'v-12',
    attemptId: 'attempt-10',
    studentId: 'student-10',
    examId: 'exam-7',
    type: 'no_face',
    severity: 'medium',
    timestamp: '2024-06-21T08:35:10Z',
    description: 'No face detected for 15 seconds',
  },
  {
    id: 'v-13',
    attemptId: 'attempt-9',
    studentId: 'student-9',
    examId: 'exam-7',
    type: 'tab_switch',
    severity: 'medium',
    timestamp: '2024-06-21T08:45:00Z',
    description: 'Student switched to another browser tab',
  },
  {
    id: 'v-14',
    attemptId: 'attempt-11',
    studentId: 'student-11',
    examId: 'exam-7',
    type: 'window_blur',
    severity: 'low',
    timestamp: '2024-06-21T09:00:22Z',
    description: 'Browser window lost focus briefly',
  },
  {
    id: 'v-15',
    attemptId: 'attempt-12',
    studentId: 'student-12',
    examId: 'exam-7',
    type: 'multiple_faces',
    severity: 'high',
    timestamp: '2024-06-21T09:18:47Z',
    description: 'Multiple faces detected — possible academic dishonesty',
  },
  {
    id: 'v-16',
    attemptId: 'attempt-13',
    studentId: 'student-3',
    examId: 'exam-3',
    type: 'tab_switch',
    severity: 'medium',
    timestamp: '2024-06-10T14:20:11Z',
    description: 'Student switched tabs during quiz',
  },
  {
    id: 'v-17',
    attemptId: 'attempt-14',
    studentId: 'student-4',
    examId: 'exam-4',
    type: 'fullscreen_exit',
    severity: 'high',
    timestamp: '2024-06-08T09:40:33Z',
    description: 'Student exited fullscreen during exam',
  },
  {
    id: 'v-18',
    attemptId: 'attempt-4',
    studentId: 'student-4',
    examId: 'exam-1',
    type: 'window_blur',
    severity: 'low',
    timestamp: '2024-06-21T10:20:00Z',
    description: 'Browser window lost focus',
  },
  {
    id: 'v-19',
    attemptId: 'attempt-1',
    studentId: 'student-1',
    examId: 'exam-1',
    type: 'audio_detected',
    severity: 'medium',
    timestamp: '2024-06-21T10:25:15Z',
    description: 'Conversational audio detected',
  },
  {
    id: 'v-20',
    attemptId: 'attempt-10',
    studentId: 'student-10',
    examId: 'exam-7',
    type: 'phone_detected',
    severity: 'high',
    timestamp: '2024-06-21T09:30:45Z',
    description: 'Phone visible in camera frame',
  },
  {
    id: 'v-21',
    attemptId: 'attempt-5',
    studentId: 'student-5',
    examId: 'exam-1',
    type: 'no_face',
    severity: 'high',
    timestamp: '2024-06-21T10:35:00Z',
    description: 'Student face not visible for extended period',
  },
  {
    id: 'v-22',
    attemptId: 'attempt-6',
    studentId: 'student-6',
    examId: 'exam-1',
    type: 'fullscreen_exit',
    severity: 'high',
    timestamp: '2024-06-21T10:40:22Z',
    description: 'Fullscreen exited — possible screen sharing',
  },
];
